import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  await prisma.apartment.createMany({
    data: [
      {
        unitName: 'Penthouse A',
        unitNumber: 'A101',
        description: 'Luxurious apartment with stunning views.',
        price: 500000,
        bedrooms: 3,
        bathrooms: 2,
        area: 150,
        images: ['/apt1.jpg', '/apt1.jpg'],
        project: 'Skyline Project',
        developer: 'Acme Developers',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2025-01-01T00:00:00.000Z'),
        street: 'Main Street',
        city: 'New York',
        country: 'USA',
        amenities: ['POOL', 'GYM', 'ELEVATOR'],
      },
      {
        unitName: 'Studio B',
        unitNumber: 'B201',
        description: 'Cozy studio perfect for singles.',
        price: 250000,
        bedrooms: 1,
        bathrooms: 1,
        area: 50,
        images: ['/apt2.jpg'],
        project: 'Urban Living',
        developer: 'Beta Builders',
        finishing: 'SEMI_FINISHED',
        deliveryDate: new Date('2025-06-01T00:00:00.000Z'),
        street: '2nd Avenue',
        city: 'Los Angeles',
        country: 'USA',
        amenities: ['GYM', 'PARKING', 'SECURITY'],
      },
      {
        unitName: 'Loft C',
        unitNumber: 'C303',
        description: 'Modern loft with open space design.',
        price: 350000,
        bedrooms: 2,
        bathrooms: 2,
        area: 100,
        images: ['/apt3.jpg', '/apt3.jpg'],
        project: 'Downtown Hub',
        developer: 'Gamma Homes',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2025-12-15T00:00:00.000Z'),
        street: 'Market Street',
        city: 'Chicago',
        country: 'USA',
        amenities: ['CLUB', 'BALCONY', 'MEDICAL_CENTER'],
      },
      {
        unitName: 'Apartment D',
        unitNumber: 'D404',
        description: 'Spacious apartment with city views.',
        price: 400000,
        bedrooms: 2,
        bathrooms: 2,
        area: 120,
        images: ['/apt4.jpg'],
        project: 'City Lights',
        developer: 'Delta Homes',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2026-03-01T00:00:00.000Z'),
        street: 'Broadway',
        city: 'New York',
        country: 'USA',
        amenities: ['POOL', 'GYM', 'SECURITY'],
      },
      {
        unitName: 'Apartment E',
        unitNumber: 'E505',
        description: 'Modern apartment in a quiet neighborhood.',
        price: 300000,
        bedrooms: 2,
        bathrooms: 1,
        area: 90,
        images: ['/apt5.jpg'],
        project: 'Green Meadows',
        developer: 'Epsilon Developments',
        finishing: 'SEMI_FINISHED',
        deliveryDate: new Date('2026-05-15T00:00:00.000Z'),
        street: 'Elm Street',
        city: 'San Francisco',
        country: 'USA',
        amenities: ['PARKING', 'ELEVATOR'],
      },
      {
        unitName: 'Apartment F',
        unitNumber: 'F606',
        description: 'Elegant apartment with classic design.',
        price: 450000,
        bedrooms: 3,
        bathrooms: 2,
        area: 140,
        images: ['/apt6.jpg'],
        project: 'Vintage Residences',
        developer: 'Zeta Constructions',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2027-01-20T00:00:00.000Z'),
        street: 'Oak Avenue',
        city: 'Chicago',
        country: 'USA',
        amenities: ['GYM', 'CLUB', 'BALCONY'],
      },
      {
        unitName: 'Apartment G',
        unitNumber: 'G707',
        description: 'Bright apartment with spacious interiors.',
        price: 350000,
        bedrooms: 2,
        bathrooms: 2,
        area: 110,
        images: ['/apt7.jpg'],
        project: 'Sunshine Towers',
        developer: 'Eta Builders',
        finishing: 'SEMI_FINISHED',
        deliveryDate: new Date('2027-04-10T00:00:00.000Z'),
        street: 'Sunset Blvd',
        city: 'Los Angeles',
        country: 'USA',
        amenities: ['POOL', 'SECURITY'],
      },
      {
        unitName: 'Apartment H',
        unitNumber: 'H808',
        description: 'Cozy apartment ideal for small families.',
        price: 320000,
        bedrooms: 2,
        bathrooms: 2,
        area: 100,
        images: ['/apt8.jpg'],
        project: 'Harmony Homes',
        developer: 'Theta Developers',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2025-09-05T00:00:00.000Z'),
        street: 'Maple Street',
        city: 'Seattle',
        country: 'USA',
        amenities: ['GYM', 'ELEVATOR', 'PARKING'],
      },
      {
        unitName: 'Apartment I',
        unitNumber: 'I909',
        description: 'Luxurious apartment with modern amenities.',
        price: 600000,
        bedrooms: 4,
        bathrooms: 3,
        area: 200,
        images: ['/apt9.jpg'],
        project: 'Royal Residences',
        developer: 'Iota Estates',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2026-11-11T00:00:00.000Z'),
        street: 'King Street',
        city: 'Boston',
        country: 'USA',
        amenities: ['POOL', 'GYM', 'CLUB', 'SECURITY'],
      },
      {
        unitName: 'Apartment J',
        unitNumber: 'J1010',
        description: 'Contemporary apartment with open plan.',
        price: 420000,
        bedrooms: 3,
        bathrooms: 2,
        area: 130,
        images: ['/apt10.jpg'],
        project: 'Modern Living',
        developer: 'Kappa Constructions',
        finishing: 'SEMI_FINISHED',
        deliveryDate: new Date('2027-07-07T00:00:00.000Z'),
        street: 'Central Avenue',
        city: 'Miami',
        country: 'USA',
        amenities: ['PARKING', 'BALCONY'],
      },
      {
        unitName: 'Apartment K',
        unitNumber: 'K1111',
        description: 'Affordable apartment with easy commute.',
        price: 280000,
        bedrooms: 1,
        bathrooms: 1,
        area: 70,
        images: ['/apt11.jpg'],
        project: 'Urban Nest',
        developer: 'Lambda Builders',
        finishing: 'UNFINISHED',
        deliveryDate: new Date('2025-04-15T00:00:00.000Z'),
        street: 'Railroad Street',
        city: 'Dallas',
        country: 'USA',
        amenities: ['ELEVATOR', 'SECURITY'],
      },
      {
        unitName: 'Apartment L',
        unitNumber: 'L1212',
        description: 'Stylish apartment in the heart of the city.',
        price: 520000,
        bedrooms: 3,
        bathrooms: 2,
        area: 160,
        images: ['/apt12.jpg'],
        project: 'City Central',
        developer: 'Mu Developments',
        finishing: 'FULLY_FINISHED',
        deliveryDate: new Date('2026-02-28T00:00:00.000Z'),
        street: 'Downtown Road',
        city: 'San Diego',
        country: 'USA',
        amenities: ['GYM', 'PARKING', 'ELEVATOR', 'BALCONY'],
      },
    ],
    skipDuplicates: true,
  });

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
